### ISSUE TITLE
The demo.rs example crashes

### ISSUE THREAD

**Issue by maximetinu** [JMS55/bevy_dioxus#1]
If I do `cargo run --example demo`

it crashes immediately, like this:

<img width="1167" alt="image" src="https://github.com/JMS55/bevy_dioxus/assets/16073309/27cd1a73-0395-4648-b334-8a2686af179b">

**Comment by JMS55** [comment]
Hey! I didn't actually expect anyone to test this project out so soon :sweat_smile:. Yes, not everything is implemented yet (mainly support for dynamic generation of nodes, and most style properties). Things like ECS access, the ECS hooks, click event handlers, and support for basic nodes and the rsx! macro works. For loops do not. If you want to test this project out, try reducing the example a bit and remove the for loop. It'll take some time, but I've been fleshing things out pretty quickly :)

**Comment by maximetinu** [comment]
hahah no worries, I just stumbled upon your post in the thread about UI support in the Bevy repo and I wanted to give it a quick try. Just to try out this dioxus library, as I've heard of it but never used it

I will give a try to simplify the demo and play with it. Thx!

**Comment by JMS55** [comment]
I've fixed a bunch of bugs and implemented some more missing features. Please try the demo now. Note, that it's expected that it will segfault when closing the app.
